language: go

go:
  - 1.7

install:
  - ./install.sh
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

env:
  global:
    secure: fd5fDwogzZNt8ZlYnS/c7X1L3DQYxxyf+JiKLz6IZDrNFsyj60iEbcqECsNgvAHPvuFA+w2oSquFikCb7uaOhwedCJEfcyzl3sYN4vuLYyJJ1GH5S97s+DJnpR9gZfnBtAGjutg3RxexZz0T+B/wFcVDnJ3cg4DopyPKvmJv3XALMw6pR0NffE+qucckEHVZtchuTNI67W/q5NkRtPPNfrT185UH2TpI060kx/uxuYEIFEsKQCWKiYZwPu2qpgTQTiKmJOlcJ084KdYM0r8GelmQUeuPvtgiZwsi0scitjBVjKeBP/gPVoUimCbAMyF0Pj26oSXa3QSaybazoZVGlG7PuGfI9mHqpaaI5n9mPM8Tzb3QNTVBDDj1VLgbz4MomP573Ofctp+uGtZJt1AQgvLg1JXPTt34JUM2IL3yZaw4z+P1vTlAoNevKaxmFir5vUedB7Pz6BNJItTKhYexX4Y/SBVK3AN82gOtRn8u8AUzpOMdDxHX3mK3MoSqqGVUCLAUR8SijePR2sc5qV78Ji9TpQx40vFTXBGJgiVKko83UQXKpNXxzmshxmFs/SpayeyjIsIMTrOdbx9gh60mlnKLgwsd2tOhNsqt8F1vzW5RB0iRk8IIhfnVMemtRtUyMZlOCZBWR1Ap5vOS2FwxgUk7hqrEwl6ujEQaJX1zJ0g=

script:
  - make test

notifications:
  email: false
