Description = "Default Dedis Cosi servers"

[[servers]]
  Addresses = ["5.135.161.91:2000"]
  Public = "6JKvBFcXS6cQ2Cz4UODC8xX5al1zittLuh97L3m8cn0="
  Description = "Nikkolasg's server: spreading the love of signing"

[[servers]]
  Addresses = ["185.26.156.40:61117"]
  Public = "zeI9zNx8PzfTtq5p3CdAAEJMq70zGt9/9W6ubhIa4pg="
  Description = "Ismail’s cosi server ... #bedeutsch"

[[servers]]
  Addresses = ["78.46.227.60:2000"]
  Public = "3LI/MDrf0T217nBzA29humeiEJM1wSipO/hBoft7e0k="
  Description = "Ineiti's Cothority Server"

[[servers]]
  Addresses = ["95.143.172.241:62306"]
  Public = "0vFiBw6KcPAXrmgxbsVhPdR08KCpj1K9i06bejPF144="
  Description = "Daeinar's Cothority Server"

