[[servers]]
  Addresses = ["192.33.210.8:7770"]
  Public = "4hTS82jGVO3DUnPyoUJjdh43ypDSwIpyOjCEXpNUfsA="
  Description = "EPFL - Cosi > v0"


[[servers]]
  Addresses = ["78.46.227.60:7770"]
  Public = "QcCaUXcNt6sM02s5dm+gPl0mLQ6BHE9g5I0BPMvj6l8="
  Description = "Profeda - Cosi > v0"
