Description = "Default Dedis Cosi servers"

[[servers]]
 Addresses = ["5.135.161.91:2000"]
 Public = "lLglU3nhHfUWe4p647hffn618TiUq+6FvTGzJw8eTGU="
 Description = "Nikkolasg's server: spreading the love of signing"

[[servers]]
  Addresses = ["185.26.156.40:61117"]
  Public = "apIWOKSt6JcOvNnjcVcPCNcaJJh/kPEjkbn2xSW+W+Q="
  Description = "Ismail's server"

[[servers]]
  Addresses = ["78.46.227.60:2000"]
  Public = "sWhBLrvgwDBwb4gsvQEqp38o1xXEuko5rjy8AqrlNWg="
  Description = "Ineiti's server"

[[servers]]
  Addresses = ["95.143.172.241:62306"]
  Public = "0vFiBw6KcPAXrmgxbsVhPdR08KCpj1K9i06bejPF144="
  Description = "Daeinar's Cothority Server"

